### ISSUE TITLE
for "external" models, put the correct model name in the output files

### ISSUE THREAD

**Issue by martinvandriel** [geodynamics/axisem#35]
for "external" models, put the correct model name in the output files

**Comment by martinvandriel** [comment]
painful, because movemesh in MESHER moves the model file to external_model.bm and the filename is hence not known in the solver. The model file does not yet contain a name field, should we add this? @sstaehler ?

**Comment by martinvandriel** [comment]
Done in the MESHER, communicating the NAME to the SOLVER requires changing the meshdb files.

**Comment by sstaehler** [comment]
And this means writing a character string of unknown length to a binary file. Yeah

**Comment by martinvandriel** [comment]
Well, we do the same with the normal background model name (where we explicitly store the length on top).

**Comment by sstaehler** [comment]
okay, then we could store the external model name there?

**Comment by martinvandriel** [comment]
Yes. I am trying to avoid to store the length explicitly and just trim it in the SOLVER...

**Comment by martinvandriel** [comment]
This was stupid....of course the name is still in the external_model.bm file. So no need to put it in the mesh. I was confused because I first wanted to use the filename of the external model file, which of course is lost.

**Comment by martinvandriel** [comment]
Do we still use simulation.info somewhere? If I add it there as well, we would need to adapt all codes reading it, I guess?

**Comment by martinvandriel** [comment]
see ef523e7c4260084c58f2fa47ceb642bccd69d67a

**Comment by sstaehler** [comment]
The kerner does not use it. Instaseis either

**Comment by martinvandriel** [comment]
Ok, so I'll just leave it anyway. Seems to be done to me.
