### ISSUE TITLE
Implementation of ak135(f) is wrong

### ISSUE THREAD

**Issue by sstaehler** [geodynamics/axisem#36]
The velocities differ from the ones in TauP at multiple depths, which causes the travel time differences compared to the latter:
See:
http://www.geophysik.uni-muenchen.de/~krischer/travel_time_issues.html

**Comment by martinvandriel** [comment]
ak135 has different velocities than ak135f, is that what you refer to?

**Comment by sstaehler** [comment]
No, it's worse. None of the ak135ves we're currently having is exactly the same as the TauP-version.

**Comment by sstaehler** [comment]
@martinvandriel: True, most of the difference between the ObsPy-TauP and Instaseis-AxiSEM traveltimes are probably due to the fact that ak135f (black) and ak135 (green) differ greatly in the upper mantle.

There is however, also a minuscule difference in vp below the 660 between ak135f from the table and our internal version (red)
![vp_table_vs_internal](https://cloud.githubusercontent.com/assets/5054072/10076763/644b124e-62dd-11e5-903a-2e3ec15b8fed.png)



It's larger in density:
![rho_table_vs_internal](https://cloud.githubusercontent.com/assets/5054072/10076766/687dd932-62dd-11e5-91d6-0e030f1c4750.png)

**Comment by sstaehler** [comment]
Okay, ak135f has a new third order polynomial for the lower mantle now which should fix this (d07d5d9e13b7f38acf66cd87efab1c1932426397). Question is whether we want to use ak135 or ak135f in the Instaseis databases.
![vp_table_vs_internal](https://cloud.githubusercontent.com/assets/5054072/10097068/b7ac7f24-6376-11e5-8897-96489886db69.png)

**Comment by martinvandriel** [comment]
I vote for ak135f, because the other one has no attenuation. Alternatively both, but how do we deal with attenuation in ak135?

**Comment by tnissen** [comment]
Just slowly picking up on all these topics... I agree, ak135f makes more 
sense.



On 9/25/15 10:51, Martin van Driel wrote:
>
> I vote for ak135f, because the other one has no attenuation. 
> Alternatively both, but how do we deal with attenuation in ak135?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/geodynamics/axisem/issues/36#issuecomment-143174859>.
>

-- 
Tarje

<>--<>--<>--<>--<>--<>
Dept. of Earth Sciences
Oxford University
South Parks Road
Oxford OX1 3AN; UK
tel: +44 1865 282149
web: seis.earth.ox.ac.uk
<>--<>--<>--<>--<>--<>
