### ISSUE TITLE
CMake Error at FindOpenMP_Fortran.cmake

### ISSUE THREAD

**Issue by jlost** [geodynamics/axisem#42]
Running RHEL 7.1 on a ppc64le machine, I get the following build error:

```
[u0017592@sys-82824 axisem]$ sudo cmake .
-- Found MPI_C: /usr/local/lib/libmpi.so
-- Found MPI_CXX: /usr/local/lib/libmpi.so
-- Found MPI_Fortran: /usr/local/lib/libmpi_usempif08.so;/usr/local/lib/libmpi_usempi_ignore_tkr.so;/usr/local/lib/libmpi_mpifh.so;/usr/local/lib/libmpi.so
-- Try OpenMP Fortran flag = [/openmp]
-- Try OpenMP Fortran flag = [/Qopenmp]
-- Try OpenMP Fortran flag = [-openmp]
CMake Error at cmake/FindOpenMP_Fortran.cmake:83 (MESSAGE):
  OpenMP found, but test code did not run
Call Stack (most recent call first):
  CMakeLists.txt:21 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!

```

Just to make sure OpenMP was kosher, I manually created the `testFortranOpenMP.f90` file that cmake generates and compiled it with `gfortran -o testFotranOpenMP -fopenmp testFortranOpenMP.f90`. It compiles successfully and its output is `2` (I do have two processors). 

It's not clear to me why CMake reports this as failing if it works when I do it manually.

**Comment by sstaehler** [comment]
Well, we never considered the CMake code production ready. They should have been removed from the code, sorry for the confusion!

Can you try to follow the instructions from the manual (run ./copy_templates.sh, modify make_axisem.macros and then use the provided Makefiles) and tell us whether this compiles on your machine.

**Comment by jlost** [comment]
Thanks, that got me much farther. I did run into a different issue, but I'll close this one out.
