### ISSUE TITLE
ld: library not found for -lnetcdf collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by davidn182** [geodynamics/axisem#54]
I am very new to programming. I am trying to install AXISEM and it has a makefile that throws me the following error:

ld: library not found for -lnetcdf
collect2: error: ld returned 1 exit status

The part of code where the error is thrown is the following
ifeq ($(strip $(USE_NETCDF)),true)
FFLAGS += -Dunc
ifdef NETCDF_PATH
LIBS = -L $(strip $(NETCDF_PATH))/lib -lnetcdff -Wl,-rpath,$(strip $(NETCDF_PATH))/lib
INCLUDE = -I $(strip $(NETCDF_PATH))/include
else
LIBS = -lnetcdff
INCLUDE = -I /usr/include
endif
else
LIBS =
INCLUDE =
endif

Thanks in advance if anyone can help me.

**Comment by sstaehler** [comment]
Hi @davidn182 ,

It seems to me, that the code cannot find netcdf. Did you install it?

**Comment by davidn182** [comment]
Hi thanks, I uninstall and reinstall netcdf and that solved the problem.

**Comment by sstaehler** [comment]
Great, I'm closing the issue
