### ISSUE TITLE
Problem compiling 

### ISSUE THREAD

**Issue by cerinunn** [geodynamics/axisem#69]
Hi, 
I'm having a problem compiling the solver. 

Running:
make SOLVER/axisem 
gives me the following error: 

mpif90 -g -fbacktrace -fbounds-check -frange-check -pedantic  -Dinclude_mpi -Dsolver -c  commpi.F90
mpif-sizeof.h:66.41:
    Included at mpif.h:63:
    Included at commpi.F90:48:

      CHARACTER, DIMENSION(1,1,1,1,1,1,1,*)::x
                                         1
Error: Array specification at (1) has more than 7 dimensions

I'm using these versions:
mpiexec --version
mpiexec (OpenRTE) 4.1.1

/usr/local/bin/mpirun -> ../Cellar/open-mpi/4.1.1_2/bin/mpirun

gcc --version
gcc (Homebrew GCC 11.2.0_1) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

netcdf library version 4.8.1 of Oct 19 2021 02:57:31
nc-config --version
netCDF 4.8.1

gcc, netcdf and open-mpi installed with Homebrew.

I'm on Mac Catalina 10.15.7.

Thanks in advance for any help,
Ceri

**Comment by martinvandriel** [comment]
Hi Ceri,

seems like an issue with the mpif.h file on you system. Maybe a workaround could be to use the mpi module instead, by setting `INCLUDE_MPI = false` in `make_axisem.macros`.

Other than that, maybe talk to an IT person at your institute, as this appears an issue with your system rather than with axsiem and I can't reproduce it.

Cheers,
Martin

**Comment by cerinunn** [comment]
Hi Martin,
Thanks for your help. I got it working with INCLUDE_MPI = false.
I think the problem was an old version of one of the compiler libraries hanging around in the path. For anyone else with a similar problem, I deleted all the compilers I could find and installed everything from scratch with Homebrew. 
Cheers, 
Ceri
